Controllers/AmenityController.cs
using Application.Common.Interfaces;
using Application.Common.Utility;
using Domain.Entities;
using Infrastructure.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.Models.ViewModels;

namespace Web.Controllers
{

    [Authorize(Roles = SD.Role_Admin)]
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AmenityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var amenities = _unitOfWork.Amenity.GetAll();
            return View(amenities);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var obj = new AmenityVM()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(v => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                })
            };
            return View(obj);
        }

        [HttpPost]
        public IActionResult Create(AmenityVM obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Add(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "The Amenity has been created successfully.";
                return RedirectToAction(nameof(Index));
            }

            obj.VillaList = _unitOfWork.Villa.GetAll().Select(v => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = v.Name,
                Value = v.Id.ToString()
            });


            return View(obj);
        }


        [HttpGet]
        public IActionResult Update(int? id)
        {
            var obj = new AmenityVM
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }),
                Amenity = _unitOfWork.Amenity.Get(a => a.Id == id)
            };

            if (obj is null)
            {
                return RedirectToAction("Error");
            }


            return View(obj);

        }

        [HttpPost]
        public IActionResult Update(AmenityVM obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Update(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "The Amenity has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }

            obj.VillaList = _unitOfWork.Villa.GetAll().Select(v => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = v.Name,
                Value = v.Id.ToString()
            });


            return View(obj);

        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {

            var obj = new AmenityVM
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }),
                Amenity = _unitOfWork.Amenity.Get(a => a.Id == id)
            };

            if (obj is null)
            {
                return RedirectToAction("Error");
            }

            return View(obj);

        }

        [HttpPost]
        public IActionResult Delete(AmenityVM obj)
        {
            var amenityDb = _unitOfWork.Amenity.Get(v => v.Id == obj.Amenity.Id);
            if (amenityDb is not null)
            {
                _unitOfWork.Amenity.Remove(amenityDb);
                _unitOfWork.Save();
                TempData["success"] = "The amenity has been deleted successfully";
                return RedirectToAction("Index");

            }
            TempData["error"] = "Couldnt not be deleted";
            return View();
        }
    }
}

Controllers/VillaNumberController.cs
using Application.Common.Interfaces;
using Domain.Entities;
using Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web.Models.ViewModels;

namespace Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public VillaNumberController(IUnitOfWork unitOfWork )
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var villaNumbers = _unitOfWork.VillaNumber.GetAll();
            return View(villaNumbers);
        }

        [HttpGet]
        public IActionResult Create()
        {

            IEnumerable<SelectListItem> list = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
            {
                Text = v.Name,
                Value = v.Id.ToString()
            });

            VillaNumberVM villaNumberVM = new VillaNumberVM
            {
                VillaList = list
            };
            return View(villaNumberVM);
        }


        [HttpPost]
        public IActionResult Create(VillaNumberVM obj)
        {
            bool roomNumberExists = _unitOfWork.VillaNumber.Any(VillaNumber => VillaNumber.Villa_Number == obj.VillaNumber.Villa_Number);

            if (ModelState.IsValid && !roomNumberExists)
            {
                _unitOfWork.VillaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "The villa Number has been created successfully.";
                return RedirectToAction(nameof(Index));
            }

            if (roomNumberExists)
            {
                TempData["error"] = "The villa Number already exists.";
            }
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
            {
                Text = v.Name,
                Value = v.Id.ToString()
            });
           
            return View(obj);
        }


        [HttpGet]
        public IActionResult Update(int? villaNumberId)
        {
            VillaNumberVM obj = new VillaNumberVM
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(v => v.Villa_Number == villaNumberId)
            };

            if(obj.VillaNumber is null)
            {
                return RedirectToAction("Error");
            }
          

            return View(obj);
        }



        [HttpPost]
        public IActionResult Update(VillaNumberVM obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.VillaNumber.Update(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "The villa Number has been created successfully.";
                return RedirectToAction(nameof(Index));
            }
            
            obj.VillaList = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
            {
                Text = v.Name,
                Value = v.Id.ToString()
            });
            return View(obj);
        }


        [HttpGet]
        public IActionResult Delete(int? villaNumberId)
        {
            VillaNumberVM obj = new VillaNumberVM
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }),
                VillaNumber = _unitOfWork.VillaNumber.Get(v => v.Villa_Number == villaNumberId)
            };
            if (obj.VillaNumber is null)
            {
                return RedirectToAction("Error");
            }

            return View(obj);
        }



        [HttpPost]
        public IActionResult Delete(VillaNumberVM obj)
        {
            var villaNumberDb = _unitOfWork.VillaNumber.Get(v => v.Villa_Number == obj.VillaNumber.Villa_Number);
            if (villaNumberDb is not null)
            {
                _unitOfWork.VillaNumber.Remove(villaNumberDb);
                _unitOfWork.Save();
                TempData["success"] = "The villa number has been deleted successfully";
                return RedirectToAction("Index");

            }
            TempData["error"] = "Couldnt not be deleted";
            return View();
        }


        public IActionResult Error()
        {
            return View();
        }

    }
}

Views/Amenity/Create.cshtml
@model AmenityVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Amenity</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div class="p-3">
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Name" class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Amenity" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Amenity/Delete.cshtml
@model AmenityVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Amenity</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input hidden asp-for="Amenity.Id" />
            <div class="p-3">
                <div class="form-floating py-1 col-12">
                    <select disabled asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input disabled asp-for="Amenity.Name" class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input disabled asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class="bi bi-check-circle"></i> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Amenity/Index.cshtml
@model IEnumerable<Amenity>


<h1>
    Amenity list
</h1>

<div class="card-body">
    <a asp-controller="Amenity" asp-action="Create" class="btn btn-primary">Create New</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Villa.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Villa.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Update" asp-controller="Amenity" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-controller="Amenity" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Amenity/Update.cshtml
@model AmenityVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Amenity</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input hidden asp-for="Amenity.Id"/>
            <div class="p-3">
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Name" class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Amenity" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}